# docker-compose.yml
version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/ypm
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:116
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A ypm worker -l info -P solo
    volumes:
      - .:/ypm
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A ypm beat -l info -P solo
    volumes:
      - .:/ypm
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
