# Generated by Django 5.1.1 on 2024-10-14 17:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_worker_initial_model'),
        ('project', '0001_project_initial_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorker',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=240, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.worker')),
            ],
            options={
                'db_table': 'projects_project_workers',
            },
        ),
    ]
