# Generated by Django 5.1.1 on 2024-10-15 08:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_worker_initial_model'),
        ('technologies', '0001_technologies_initial_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('technology', models.ForeignKey(db_column='technology', on_delete=django.db.models.deletion.CASCADE, to='technologies.technology')),
            ],
            options={
                'db_table': 'projects_project_technologies',
            },
        ),
    ]
