# Generated by Django 5.1.1 on 2024-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_department_initial_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
