# Generated by Django 5.1.1 on 2024-10-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_phase_initial_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='phase',
            field=models.ForeignKey(db_column='phase', on_delete=django.db.models.deletion.CASCADE, to='project.projectphase'),
            preserve_default=False,
        ),
    ]
