# Generated by Django 5.1.1 on 2024-10-24 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_task_phase_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='department',
            field=models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.CASCADE, to='project.projectdepartment'),
            preserve_default=False,
        ),
    ]
