# Generated by Django 5.1.1 on 2024-10-29 11:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_task_department_new_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJira',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=240)),
                ('name', models.CharField(max_length=240)),
                ('project', models.OneToOneField(db_column='project', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'projects_project_jira',
                'unique_together': {('key', 'project')},
            },
        ),
    ]
