# Generated by Django 5.1.1 on 2024-10-30 11:26

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_jira_initial_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskWorker',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.ForeignKey(db_column='task', on_delete=django.db.models.deletion.CASCADE, to='project.projecttask')),
                ('worker', models.ForeignKey(db_column='worker', on_delete=django.db.models.deletion.CASCADE, to='company.worker')),
            ],
            options={
                'db_table': 'projects_project_task_workers',
            },
        ),
    ]
