# Generated by Django 5.1.1 on 2024-11-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_requirement_initial_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsprint',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectsprint',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectsprint',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
