# Generated by Django 5.1.1 on 2024-10-14 08:30

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_company_initial_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departments_department',
            },
        ),
    ]
