# Generated by Django 5.1.1 on 2024-10-30 12:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_worker_initial_model'),
        ('technologies', '0001_technologies_initial_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTechnology',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technology', models.ForeignKey(db_column='technology', on_delete=django.db.models.deletion.CASCADE, to='technologies.technology')),
                ('worker', models.ForeignKey(db_column='worker', on_delete=django.db.models.deletion.CASCADE, to='company.worker')),
            ],
            options={
                'db_table': 'companies_worker_technology',
            },
        ),
    ]
