# Generated by Django 5.1.1 on 2024-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_worker_technology_initial_model'),
        ('technologies', '0001_technologies_initial_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='technologies',
            field=models.ManyToManyField(blank=True, through='company.WorkerTechnology', to='technologies.technology'),
        ),
    ]
