services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - /var/www/Backend-YPM/ypm/static/:/app/staticfiles/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A ypm worker -l info -P prefork
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A ypm beat -l info
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
